class test
    public static function test1() : void
        throw exception.createException(-1, "exception from factory");
    end

    public static function getError() : exception
        return exception.createException(-2, "exception from static call");
    end

    public static function test2() : void
        throw getError();
    end

    public static function test3() : void
        var ex : exception;
        ex = new exception();
        ex.code = -3;
        ex.message = "exception from variable";

        throw ex;
    end
end